### ISSUE TITLE
Fixing the Last Item in Your Places List

### ISSUE THREAD

**Issue by MarcoMorawec** [JonnShaft/nomster#1]
It looks like your last 2 places are nested in the same div.

Here's what I'm seeing:

![screen shot 2015-06-24 at 11 39 26 am](https://cloud.githubusercontent.com/assets/1474717/8334446/ff4821da-1a65-11e5-93c5-b9b5f5938e4b.png)

**Comment by JonnShaft** [comment]
All fixed.
